pipeline:
  html:
    image: busybox
    commands:
      - install -D index.html dist/index.html
  node:
    image: node
    commands:
      - npm install
      - npm run-script build
  python:
    image: base/archlinux
    commands:
      - pacman -Syu --noconfirm
      - pacman -S --noconfirm eigen emscripten grep python-pip
      - pip install chainercv webdnn
      - |
        PATH=/usr/lib/emscripten:$PATH \
        CPLUS_INCLUDE_PATH=/usr/include/eigen3 \
        python convert.py --out dist/model --backend webgl webassembly | grep -vE '\r'
