pipeline:
  html:
    image: busybox
    commands:
      - install -D index.html dist/index.html
  node:
    image: node
    commands:
      - npm install
      - npm run-script build
  python:
    image: python
    commands:
      - pip install chainercv webdnn
      - apt-get update
      - apt-get install -y --no-install-recommends emscripten libeigen3-dev
      - python convert.py --out dist/model --backend webgl webassembly
