pipeline:
  node:
    image: node
    commands:
      - npm install
      - npm run-script build
  python:
    image: python
    commands:
      - pip install chainercv webdnn
      - python convert.py --out dist/model --backend webgl
